# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - aptly
  pillars:
    top.sls:
      base:
        "*":
          - aptly

platforms:
  - name: bento/debian-8.8

suites:
  - name: default
    provisioner:
      pillars:
        aptly.sls:
          aptly:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        aptly.sls: pillar-custom.sls
